// <auto-generated />
namespace Emando.Vantage.Components.Competitions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LongCategoryFilter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LongCategoryFilter));
        
        string IMigrationMetadata.Id
        {
            get { return "201710271523106_LongCategoryFilter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
