//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Windows.Controls.Competitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Windows.Controls.Competitions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        internal static string TimeInfo_1 {
            get {
                return ResourceManager.GetString("TimeInfo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        internal static string TimeInfo_16 {
            get {
                return ResourceManager.GetString("TimeInfo_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS.
        /// </summary>
        internal static string TimeInfo_2 {
            get {
                return ResourceManager.GetString("TimeInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WR.
        /// </summary>
        internal static string TimeInfo_32 {
            get {
                return ResourceManager.GetString("TimeInfo_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        internal static string TimeInfo_4 {
            get {
                return ResourceManager.GetString("TimeInfo_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        internal static string TimeInfo_8 {
            get {
                return ResourceManager.GetString("TimeInfo_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??.
        /// </summary>
        internal static string TimeInvalidReason_0 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NS.
        /// </summary>
        internal static string TimeInvalidReason_1 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF.
        /// </summary>
        internal static string TimeInvalidReason_2 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DQ.
        /// </summary>
        internal static string TimeInvalidReason_3 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WD.
        /// </summary>
        internal static string TimeInvalidReason_4 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_4", resourceCulture);
            }
        }
    }
}
