//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Workflows.Competitions.SpeedSkating.LongTrack.Reporting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Workflows.Competitions.SpeedSkating.LongTrack.Reporting.Properties" +
                            ".Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wt.
        /// </summary>
        internal static string Color_0 {
            get {
                return ResourceManager.GetString("Color_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rd.
        /// </summary>
        internal static string Color_1 {
            get {
                return ResourceManager.GetString("Color_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yw.
        /// </summary>
        internal static string Color_2 {
            get {
                return ResourceManager.GetString("Color_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bl.
        /// </summary>
        internal static string Color_3 {
            get {
                return ResourceManager.GetString("Color_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - grouped.
        /// </summary>
        internal static string CompetitorGroupTitle {
            get {
                return ResourceManager.GetString("CompetitorGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - competitors.
        /// </summary>
        internal static string CompetitorListTitle {
            get {
                return ResourceManager.GetString("CompetitorListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string Dates_MultipleDays {
            get {
                return ResourceManager.GetString("Dates_MultipleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        internal static string Dates_TwoDays {
            get {
                return ResourceManager.GetString("Dates_TwoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - draw.
        /// </summary>
        internal static string DrawTitle {
            get {
                return ResourceManager.GetString("DrawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - fill in.
        /// </summary>
        internal static string FillInTitle {
            get {
                return ResourceManager.GetString("FillInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string Lane_0 {
            get {
                return ResourceManager.GetString("Lane_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string Lane_1 {
            get {
                return ResourceManager.GetString("Lane_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string OptionalColumn_1 {
            get {
                return ResourceManager.GetString("OptionalColumn_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string OptionalColumn_16 {
            get {
                return ResourceManager.GetString("OptionalColumn_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string OptionalColumn_2 {
            get {
                return ResourceManager.GetString("OptionalColumn_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SB.
        /// </summary>
        internal static string OptionalColumn_32 {
            get {
                return ResourceManager.GetString("OptionalColumn_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string OptionalColumn_4 {
            get {
                return ResourceManager.GetString("OptionalColumn_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (S{1}).
        /// </summary>
        internal static string ReserveFormat {
            get {
                return ResourceManager.GetString("ReserveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - result.
        /// </summary>
        internal static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        internal static string TimeInfo_1 {
            get {
                return ResourceManager.GetString("TimeInfo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string TimeInfo_128 {
            get {
                return ResourceManager.GetString("TimeInfo_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        internal static string TimeInfo_16 {
            get {
                return ResourceManager.GetString("TimeInfo_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS.
        /// </summary>
        internal static string TimeInfo_2 {
            get {
                return ResourceManager.GetString("TimeInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRC.
        /// </summary>
        internal static string TimeInfo_256 {
            get {
                return ResourceManager.GetString("TimeInfo_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WR.
        /// </summary>
        internal static string TimeInfo_32 {
            get {
                return ResourceManager.GetString("TimeInfo_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        internal static string TimeInfo_4 {
            get {
                return ResourceManager.GetString("TimeInfo_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OC.
        /// </summary>
        internal static string TimeInfo_64 {
            get {
                return ResourceManager.GetString("TimeInfo_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        internal static string TimeInfo_8 {
            get {
                return ResourceManager.GetString("TimeInfo_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        internal static string TimeInvalidReason_1 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNF.
        /// </summary>
        internal static string TimeInvalidReason_2 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DQ.
        /// </summary>
        internal static string TimeInvalidReason_3 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WDR.
        /// </summary>
        internal static string TimeInvalidReason_4 {
            get {
                return ResourceManager.GetString("TimeInvalidReason_4", resourceCulture);
            }
        }
    }
}
