//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Components.Competitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Components.Competitions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified competition could not be found..
        /// </summary>
        internal static string CompetitionNotFound {
            get {
                return ResourceManager.GetString("CompetitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified competition serie could not be found..
        /// </summary>
        internal static string CompetitionSerieNotFound {
            get {
                return ResourceManager.GetString("CompetitionSerieNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified competitor could not be found..
        /// </summary>
        internal static string CompetitorNotFound {
            get {
                return ResourceManager.GetString("CompetitorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified distance combination could not be found..
        /// </summary>
        internal static string DistanceCombinationNotFound {
            get {
                return ResourceManager.GetString("DistanceCombinationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified distance has results..
        /// </summary>
        internal static string DistanceHasResults {
            get {
                return ResourceManager.GetString("DistanceHasResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified distance could not be found..
        /// </summary>
        internal static string DistanceNotFound {
            get {
                return ResourceManager.GetString("DistanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified draw mode is not supported..
        /// </summary>
        internal static string DrawModeNotSupported {
            get {
                return ResourceManager.GetString("DrawModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified draw spreading is not supported..
        /// </summary>
        internal static string DrawSpreadingNotSupported {
            get {
                return ResourceManager.GetString("DrawSpreadingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat {0}.
        /// </summary>
        internal static string HeatName {
            get {
                return ResourceManager.GetString("HeatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid competition results state..
        /// </summary>
        internal static string InvalidCompetitionResultsState {
            get {
                return ResourceManager.GetString("InvalidCompetitionResultsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The race result is invalid; either specify a time or a time invalid reason for committed races..
        /// </summary>
        internal static string InvalidRaceResult {
            get {
                return ResourceManager.GetString("InvalidRaceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified presentation source could not be found..
        /// </summary>
        internal static string PresentationSourceNotFound {
            get {
                return ResourceManager.GetString("PresentationSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified presentation source is not supported..
        /// </summary>
        internal static string PresentationSourceNotSupported {
            get {
                return ResourceManager.GetString("PresentationSourceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        internal static string QualificationsToFinal_RoundsToGo_0 {
            get {
                return ResourceManager.GetString("QualificationsToFinal_RoundsToGo_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        internal static string QualificationsToFinal_RoundsToGo_Other {
            get {
                return ResourceManager.GetString("QualificationsToFinal_RoundsToGo_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified race could not be found..
        /// </summary>
        internal static string RaceNotFound {
            get {
                return ResourceManager.GetString("RaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        internal static string SingleElimination_RoundsToGo_0 {
            get {
                return ResourceManager.GetString("SingleElimination_RoundsToGo_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-finals.
        /// </summary>
        internal static string SingleElimination_RoundsToGo_1 {
            get {
                return ResourceManager.GetString("SingleElimination_RoundsToGo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter-finals.
        /// </summary>
        internal static string SingleElimination_RoundsToGo_2 {
            get {
                return ResourceManager.GetString("SingleElimination_RoundsToGo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8th-finals.
        /// </summary>
        internal static string SingleElimination_RoundsToGo_3 {
            get {
                return ResourceManager.GetString("SingleElimination_RoundsToGo_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16th-finals.
        /// </summary>
        internal static string SingleElimination_RoundsToGo_4 {
            get {
                return ResourceManager.GetString("SingleElimination_RoundsToGo_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32nd-final.
        /// </summary>
        internal static string SingleElimination_RoundsToGo_5 {
            get {
                return ResourceManager.GetString("SingleElimination_RoundsToGo_5", resourceCulture);
            }
        }
    }
}
