//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Web.Competitions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Web.Competitions.Resources.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Afghanistan.
        /// </summary>
        internal static string CountryCode_AFG {
            get {
                return ResourceManager.GetString("CountryCode_AFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Albania.
        /// </summary>
        internal static string CountryCode_ALB {
            get {
                return ResourceManager.GetString("CountryCode_ALB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Algeria.
        /// </summary>
        internal static string CountryCode_ALG {
            get {
                return ResourceManager.GetString("CountryCode_ALG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Andorra.
        /// </summary>
        internal static string CountryCode_AND {
            get {
                return ResourceManager.GetString("CountryCode_AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Angola.
        /// </summary>
        internal static string CountryCode_ANG {
            get {
                return ResourceManager.GetString("CountryCode_ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Antigua and Barbuda.
        /// </summary>
        internal static string CountryCode_ANT {
            get {
                return ResourceManager.GetString("CountryCode_ANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Argentina.
        /// </summary>
        internal static string CountryCode_ARG {
            get {
                return ResourceManager.GetString("CountryCode_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Armenia.
        /// </summary>
        internal static string CountryCode_ARM {
            get {
                return ResourceManager.GetString("CountryCode_ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Aruba.
        /// </summary>
        internal static string CountryCode_ARU {
            get {
                return ResourceManager.GetString("CountryCode_ARU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  American Samoa.
        /// </summary>
        internal static string CountryCode_ASA {
            get {
                return ResourceManager.GetString("CountryCode_ASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Australia.
        /// </summary>
        internal static string CountryCode_AUS {
            get {
                return ResourceManager.GetString("CountryCode_AUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Austria.
        /// </summary>
        internal static string CountryCode_AUT {
            get {
                return ResourceManager.GetString("CountryCode_AUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Azerbaijan.
        /// </summary>
        internal static string CountryCode_AZE {
            get {
                return ResourceManager.GetString("CountryCode_AZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bahamas.
        /// </summary>
        internal static string CountryCode_BAH {
            get {
                return ResourceManager.GetString("CountryCode_BAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bangladesh.
        /// </summary>
        internal static string CountryCode_BAN {
            get {
                return ResourceManager.GetString("CountryCode_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Barbados.
        /// </summary>
        internal static string CountryCode_BAR {
            get {
                return ResourceManager.GetString("CountryCode_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Burundi.
        /// </summary>
        internal static string CountryCode_BDI {
            get {
                return ResourceManager.GetString("CountryCode_BDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Belgium.
        /// </summary>
        internal static string CountryCode_BEL {
            get {
                return ResourceManager.GetString("CountryCode_BEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Benin.
        /// </summary>
        internal static string CountryCode_BEN {
            get {
                return ResourceManager.GetString("CountryCode_BEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bermuda.
        /// </summary>
        internal static string CountryCode_BER {
            get {
                return ResourceManager.GetString("CountryCode_BER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bhutan.
        /// </summary>
        internal static string CountryCode_BHU {
            get {
                return ResourceManager.GetString("CountryCode_BHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bosnia and Herzegovina.
        /// </summary>
        internal static string CountryCode_BIH {
            get {
                return ResourceManager.GetString("CountryCode_BIH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Belize.
        /// </summary>
        internal static string CountryCode_BIZ {
            get {
                return ResourceManager.GetString("CountryCode_BIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Belarus.
        /// </summary>
        internal static string CountryCode_BLR {
            get {
                return ResourceManager.GetString("CountryCode_BLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bolivia.
        /// </summary>
        internal static string CountryCode_BOL {
            get {
                return ResourceManager.GetString("CountryCode_BOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Botswana.
        /// </summary>
        internal static string CountryCode_BOT {
            get {
                return ResourceManager.GetString("CountryCode_BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Brazil.
        /// </summary>
        internal static string CountryCode_BRA {
            get {
                return ResourceManager.GetString("CountryCode_BRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bahrain.
        /// </summary>
        internal static string CountryCode_BRN {
            get {
                return ResourceManager.GetString("CountryCode_BRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Brunei.
        /// </summary>
        internal static string CountryCode_BRU {
            get {
                return ResourceManager.GetString("CountryCode_BRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bulgaria.
        /// </summary>
        internal static string CountryCode_BUL {
            get {
                return ResourceManager.GetString("CountryCode_BUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Burkina Faso.
        /// </summary>
        internal static string CountryCode_BUR {
            get {
                return ResourceManager.GetString("CountryCode_BUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Central African Republic.
        /// </summary>
        internal static string CountryCode_CAF {
            get {
                return ResourceManager.GetString("CountryCode_CAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cambodia.
        /// </summary>
        internal static string CountryCode_CAM {
            get {
                return ResourceManager.GetString("CountryCode_CAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Canada.
        /// </summary>
        internal static string CountryCode_CAN {
            get {
                return ResourceManager.GetString("CountryCode_CAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cayman Islands.
        /// </summary>
        internal static string CountryCode_CAY {
            get {
                return ResourceManager.GetString("CountryCode_CAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Congo.
        /// </summary>
        internal static string CountryCode_CGO {
            get {
                return ResourceManager.GetString("CountryCode_CGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chad.
        /// </summary>
        internal static string CountryCode_CHA {
            get {
                return ResourceManager.GetString("CountryCode_CHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chile.
        /// </summary>
        internal static string CountryCode_CHI {
            get {
                return ResourceManager.GetString("CountryCode_CHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  China.
        /// </summary>
        internal static string CountryCode_CHN {
            get {
                return ResourceManager.GetString("CountryCode_CHN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ivory Coast.
        /// </summary>
        internal static string CountryCode_CIV {
            get {
                return ResourceManager.GetString("CountryCode_CIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cameroon.
        /// </summary>
        internal static string CountryCode_CMR {
            get {
                return ResourceManager.GetString("CountryCode_CMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DR Congo.
        /// </summary>
        internal static string CountryCode_COD {
            get {
                return ResourceManager.GetString("CountryCode_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cook Islands.
        /// </summary>
        internal static string CountryCode_COK {
            get {
                return ResourceManager.GetString("CountryCode_COK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Colombia.
        /// </summary>
        internal static string CountryCode_COL {
            get {
                return ResourceManager.GetString("CountryCode_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Comoros.
        /// </summary>
        internal static string CountryCode_COM {
            get {
                return ResourceManager.GetString("CountryCode_COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cape Verde.
        /// </summary>
        internal static string CountryCode_CPV {
            get {
                return ResourceManager.GetString("CountryCode_CPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Costa Rica.
        /// </summary>
        internal static string CountryCode_CRC {
            get {
                return ResourceManager.GetString("CountryCode_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Croatia.
        /// </summary>
        internal static string CountryCode_CRO {
            get {
                return ResourceManager.GetString("CountryCode_CRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cuba.
        /// </summary>
        internal static string CountryCode_CUB {
            get {
                return ResourceManager.GetString("CountryCode_CUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cyprus.
        /// </summary>
        internal static string CountryCode_CYP {
            get {
                return ResourceManager.GetString("CountryCode_CYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Czech Republic.
        /// </summary>
        internal static string CountryCode_CZE {
            get {
                return ResourceManager.GetString("CountryCode_CZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Denmark.
        /// </summary>
        internal static string CountryCode_DEN {
            get {
                return ResourceManager.GetString("CountryCode_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Djibouti.
        /// </summary>
        internal static string CountryCode_DJI {
            get {
                return ResourceManager.GetString("CountryCode_DJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dominica.
        /// </summary>
        internal static string CountryCode_DMA {
            get {
                return ResourceManager.GetString("CountryCode_DMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dominican Republic.
        /// </summary>
        internal static string CountryCode_DOM {
            get {
                return ResourceManager.GetString("CountryCode_DOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ecuador.
        /// </summary>
        internal static string CountryCode_ECU {
            get {
                return ResourceManager.GetString("CountryCode_ECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Egypt.
        /// </summary>
        internal static string CountryCode_EGY {
            get {
                return ResourceManager.GetString("CountryCode_EGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Eritrea.
        /// </summary>
        internal static string CountryCode_ERI {
            get {
                return ResourceManager.GetString("CountryCode_ERI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  El Salvador.
        /// </summary>
        internal static string CountryCode_ESA {
            get {
                return ResourceManager.GetString("CountryCode_ESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Spain.
        /// </summary>
        internal static string CountryCode_ESP {
            get {
                return ResourceManager.GetString("CountryCode_ESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Estonia.
        /// </summary>
        internal static string CountryCode_EST {
            get {
                return ResourceManager.GetString("CountryCode_EST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ethiopia.
        /// </summary>
        internal static string CountryCode_ETH {
            get {
                return ResourceManager.GetString("CountryCode_ETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Fiji.
        /// </summary>
        internal static string CountryCode_FIJ {
            get {
                return ResourceManager.GetString("CountryCode_FIJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Finland.
        /// </summary>
        internal static string CountryCode_FIN {
            get {
                return ResourceManager.GetString("CountryCode_FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  France.
        /// </summary>
        internal static string CountryCode_FRA {
            get {
                return ResourceManager.GetString("CountryCode_FRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Federated States of Micronesia.
        /// </summary>
        internal static string CountryCode_FSM {
            get {
                return ResourceManager.GetString("CountryCode_FSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gabon.
        /// </summary>
        internal static string CountryCode_GAB {
            get {
                return ResourceManager.GetString("CountryCode_GAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The Gambia.
        /// </summary>
        internal static string CountryCode_GAM {
            get {
                return ResourceManager.GetString("CountryCode_GAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Great Britain.
        /// </summary>
        internal static string CountryCode_GBR {
            get {
                return ResourceManager.GetString("CountryCode_GBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Guinea-Bissau.
        /// </summary>
        internal static string CountryCode_GBS {
            get {
                return ResourceManager.GetString("CountryCode_GBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Georgia.
        /// </summary>
        internal static string CountryCode_GEO {
            get {
                return ResourceManager.GetString("CountryCode_GEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Equatorial Guinea.
        /// </summary>
        internal static string CountryCode_GEQ {
            get {
                return ResourceManager.GetString("CountryCode_GEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Germany.
        /// </summary>
        internal static string CountryCode_GER {
            get {
                return ResourceManager.GetString("CountryCode_GER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ghana.
        /// </summary>
        internal static string CountryCode_GHA {
            get {
                return ResourceManager.GetString("CountryCode_GHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Greece.
        /// </summary>
        internal static string CountryCode_GRE {
            get {
                return ResourceManager.GetString("CountryCode_GRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Grenada.
        /// </summary>
        internal static string CountryCode_GRN {
            get {
                return ResourceManager.GetString("CountryCode_GRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Guatemala.
        /// </summary>
        internal static string CountryCode_GUA {
            get {
                return ResourceManager.GetString("CountryCode_GUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Guinea.
        /// </summary>
        internal static string CountryCode_GUI {
            get {
                return ResourceManager.GetString("CountryCode_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Guam.
        /// </summary>
        internal static string CountryCode_GUM {
            get {
                return ResourceManager.GetString("CountryCode_GUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Guyana.
        /// </summary>
        internal static string CountryCode_GUY {
            get {
                return ResourceManager.GetString("CountryCode_GUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Haiti.
        /// </summary>
        internal static string CountryCode_HAI {
            get {
                return ResourceManager.GetString("CountryCode_HAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hong Kong.
        /// </summary>
        internal static string CountryCode_HKG {
            get {
                return ResourceManager.GetString("CountryCode_HKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Honduras.
        /// </summary>
        internal static string CountryCode_HON {
            get {
                return ResourceManager.GetString("CountryCode_HON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hungary.
        /// </summary>
        internal static string CountryCode_HUN {
            get {
                return ResourceManager.GetString("CountryCode_HUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Indonesia.
        /// </summary>
        internal static string CountryCode_INA {
            get {
                return ResourceManager.GetString("CountryCode_INA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  India.
        /// </summary>
        internal static string CountryCode_IND {
            get {
                return ResourceManager.GetString("CountryCode_IND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Iran.
        /// </summary>
        internal static string CountryCode_IRI {
            get {
                return ResourceManager.GetString("CountryCode_IRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ireland.
        /// </summary>
        internal static string CountryCode_IRL {
            get {
                return ResourceManager.GetString("CountryCode_IRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Iraq.
        /// </summary>
        internal static string CountryCode_IRQ {
            get {
                return ResourceManager.GetString("CountryCode_IRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Iceland.
        /// </summary>
        internal static string CountryCode_ISL {
            get {
                return ResourceManager.GetString("CountryCode_ISL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Israel.
        /// </summary>
        internal static string CountryCode_ISR {
            get {
                return ResourceManager.GetString("CountryCode_ISR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Virgin Islands.
        /// </summary>
        internal static string CountryCode_ISV {
            get {
                return ResourceManager.GetString("CountryCode_ISV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Italy.
        /// </summary>
        internal static string CountryCode_ITA {
            get {
                return ResourceManager.GetString("CountryCode_ITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  British Virgin Islands.
        /// </summary>
        internal static string CountryCode_IVB {
            get {
                return ResourceManager.GetString("CountryCode_IVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Jamaica.
        /// </summary>
        internal static string CountryCode_JAM {
            get {
                return ResourceManager.GetString("CountryCode_JAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Jordan.
        /// </summary>
        internal static string CountryCode_JOR {
            get {
                return ResourceManager.GetString("CountryCode_JOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Japan.
        /// </summary>
        internal static string CountryCode_JPN {
            get {
                return ResourceManager.GetString("CountryCode_JPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kazakhstan.
        /// </summary>
        internal static string CountryCode_KAZ {
            get {
                return ResourceManager.GetString("CountryCode_KAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kenya.
        /// </summary>
        internal static string CountryCode_KEN {
            get {
                return ResourceManager.GetString("CountryCode_KEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kyrgyzstan.
        /// </summary>
        internal static string CountryCode_KGZ {
            get {
                return ResourceManager.GetString("CountryCode_KGZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kiribati.
        /// </summary>
        internal static string CountryCode_KIR {
            get {
                return ResourceManager.GetString("CountryCode_KIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  South Korea.
        /// </summary>
        internal static string CountryCode_KOR {
            get {
                return ResourceManager.GetString("CountryCode_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kosovo.
        /// </summary>
        internal static string CountryCode_KOS {
            get {
                return ResourceManager.GetString("CountryCode_KOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saudi Arabia.
        /// </summary>
        internal static string CountryCode_KSA {
            get {
                return ResourceManager.GetString("CountryCode_KSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Kuwait.
        /// </summary>
        internal static string CountryCode_KUW {
            get {
                return ResourceManager.GetString("CountryCode_KUW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Laos.
        /// </summary>
        internal static string CountryCode_LAO {
            get {
                return ResourceManager.GetString("CountryCode_LAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Latvia.
        /// </summary>
        internal static string CountryCode_LAT {
            get {
                return ResourceManager.GetString("CountryCode_LAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Libya.
        /// </summary>
        internal static string CountryCode_LBA {
            get {
                return ResourceManager.GetString("CountryCode_LBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Liberia.
        /// </summary>
        internal static string CountryCode_LBR {
            get {
                return ResourceManager.GetString("CountryCode_LBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saint Lucia.
        /// </summary>
        internal static string CountryCode_LCA {
            get {
                return ResourceManager.GetString("CountryCode_LCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lesotho.
        /// </summary>
        internal static string CountryCode_LES {
            get {
                return ResourceManager.GetString("CountryCode_LES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lebanon.
        /// </summary>
        internal static string CountryCode_LIB {
            get {
                return ResourceManager.GetString("CountryCode_LIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Liechtenstein.
        /// </summary>
        internal static string CountryCode_LIE {
            get {
                return ResourceManager.GetString("CountryCode_LIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lithuania.
        /// </summary>
        internal static string CountryCode_LTU {
            get {
                return ResourceManager.GetString("CountryCode_LTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Luxembourg.
        /// </summary>
        internal static string CountryCode_LUX {
            get {
                return ResourceManager.GetString("CountryCode_LUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Madagascar.
        /// </summary>
        internal static string CountryCode_MAD {
            get {
                return ResourceManager.GetString("CountryCode_MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Morocco.
        /// </summary>
        internal static string CountryCode_MAR {
            get {
                return ResourceManager.GetString("CountryCode_MAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Malaysia.
        /// </summary>
        internal static string CountryCode_MAS {
            get {
                return ResourceManager.GetString("CountryCode_MAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Malawi.
        /// </summary>
        internal static string CountryCode_MAW {
            get {
                return ResourceManager.GetString("CountryCode_MAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Moldova.
        /// </summary>
        internal static string CountryCode_MDA {
            get {
                return ResourceManager.GetString("CountryCode_MDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Maldives.
        /// </summary>
        internal static string CountryCode_MDV {
            get {
                return ResourceManager.GetString("CountryCode_MDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mexico.
        /// </summary>
        internal static string CountryCode_MEX {
            get {
                return ResourceManager.GetString("CountryCode_MEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mongolia.
        /// </summary>
        internal static string CountryCode_MGL {
            get {
                return ResourceManager.GetString("CountryCode_MGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Marshall Islands.
        /// </summary>
        internal static string CountryCode_MHL {
            get {
                return ResourceManager.GetString("CountryCode_MHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Macedonia.
        /// </summary>
        internal static string CountryCode_MKD {
            get {
                return ResourceManager.GetString("CountryCode_MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mali.
        /// </summary>
        internal static string CountryCode_MLI {
            get {
                return ResourceManager.GetString("CountryCode_MLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Malta.
        /// </summary>
        internal static string CountryCode_MLT {
            get {
                return ResourceManager.GetString("CountryCode_MLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Montenegro.
        /// </summary>
        internal static string CountryCode_MNE {
            get {
                return ResourceManager.GetString("CountryCode_MNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Monaco.
        /// </summary>
        internal static string CountryCode_MON {
            get {
                return ResourceManager.GetString("CountryCode_MON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mozambique.
        /// </summary>
        internal static string CountryCode_MOZ {
            get {
                return ResourceManager.GetString("CountryCode_MOZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mauritius.
        /// </summary>
        internal static string CountryCode_MRI {
            get {
                return ResourceManager.GetString("CountryCode_MRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mauritania.
        /// </summary>
        internal static string CountryCode_MTN {
            get {
                return ResourceManager.GetString("CountryCode_MTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Myanmar.
        /// </summary>
        internal static string CountryCode_MYA {
            get {
                return ResourceManager.GetString("CountryCode_MYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Namibia.
        /// </summary>
        internal static string CountryCode_NAM {
            get {
                return ResourceManager.GetString("CountryCode_NAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nicaragua.
        /// </summary>
        internal static string CountryCode_NCA {
            get {
                return ResourceManager.GetString("CountryCode_NCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Netherlands.
        /// </summary>
        internal static string CountryCode_NED {
            get {
                return ResourceManager.GetString("CountryCode_NED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nepal.
        /// </summary>
        internal static string CountryCode_NEP {
            get {
                return ResourceManager.GetString("CountryCode_NEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nigeria.
        /// </summary>
        internal static string CountryCode_NGR {
            get {
                return ResourceManager.GetString("CountryCode_NGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Niger.
        /// </summary>
        internal static string CountryCode_NIG {
            get {
                return ResourceManager.GetString("CountryCode_NIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Norway.
        /// </summary>
        internal static string CountryCode_NOR {
            get {
                return ResourceManager.GetString("CountryCode_NOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nauru.
        /// </summary>
        internal static string CountryCode_NRU {
            get {
                return ResourceManager.GetString("CountryCode_NRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  New Zealand.
        /// </summary>
        internal static string CountryCode_NZL {
            get {
                return ResourceManager.GetString("CountryCode_NZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Oman.
        /// </summary>
        internal static string CountryCode_OMA {
            get {
                return ResourceManager.GetString("CountryCode_OMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Pakistan.
        /// </summary>
        internal static string CountryCode_PAK {
            get {
                return ResourceManager.GetString("CountryCode_PAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Panama.
        /// </summary>
        internal static string CountryCode_PAN {
            get {
                return ResourceManager.GetString("CountryCode_PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Paraguay.
        /// </summary>
        internal static string CountryCode_PAR {
            get {
                return ResourceManager.GetString("CountryCode_PAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Peru.
        /// </summary>
        internal static string CountryCode_PER {
            get {
                return ResourceManager.GetString("CountryCode_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Philippines.
        /// </summary>
        internal static string CountryCode_PHI {
            get {
                return ResourceManager.GetString("CountryCode_PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Palestine.
        /// </summary>
        internal static string CountryCode_PLE {
            get {
                return ResourceManager.GetString("CountryCode_PLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Palau.
        /// </summary>
        internal static string CountryCode_PLW {
            get {
                return ResourceManager.GetString("CountryCode_PLW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Papua New Guinea.
        /// </summary>
        internal static string CountryCode_PNG {
            get {
                return ResourceManager.GetString("CountryCode_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Poland.
        /// </summary>
        internal static string CountryCode_POL {
            get {
                return ResourceManager.GetString("CountryCode_POL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Portugal.
        /// </summary>
        internal static string CountryCode_POR {
            get {
                return ResourceManager.GetString("CountryCode_POR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  North Korea.
        /// </summary>
        internal static string CountryCode_PRK {
            get {
                return ResourceManager.GetString("CountryCode_PRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Puerto Rico.
        /// </summary>
        internal static string CountryCode_PUR {
            get {
                return ResourceManager.GetString("CountryCode_PUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Qatar.
        /// </summary>
        internal static string CountryCode_QAT {
            get {
                return ResourceManager.GetString("CountryCode_QAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Romania.
        /// </summary>
        internal static string CountryCode_ROU {
            get {
                return ResourceManager.GetString("CountryCode_ROU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  South Africa.
        /// </summary>
        internal static string CountryCode_RSA {
            get {
                return ResourceManager.GetString("CountryCode_RSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Russia.
        /// </summary>
        internal static string CountryCode_RUS {
            get {
                return ResourceManager.GetString("CountryCode_RUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Rwanda.
        /// </summary>
        internal static string CountryCode_RWA {
            get {
                return ResourceManager.GetString("CountryCode_RWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Samoa.
        /// </summary>
        internal static string CountryCode_SAM {
            get {
                return ResourceManager.GetString("CountryCode_SAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Senegal.
        /// </summary>
        internal static string CountryCode_SEN {
            get {
                return ResourceManager.GetString("CountryCode_SEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Seychelles.
        /// </summary>
        internal static string CountryCode_SEY {
            get {
                return ResourceManager.GetString("CountryCode_SEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Singapore.
        /// </summary>
        internal static string CountryCode_SIN {
            get {
                return ResourceManager.GetString("CountryCode_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saint Kitts and Nevis.
        /// </summary>
        internal static string CountryCode_SKN {
            get {
                return ResourceManager.GetString("CountryCode_SKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sierra Leone.
        /// </summary>
        internal static string CountryCode_SLE {
            get {
                return ResourceManager.GetString("CountryCode_SLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Slovenia.
        /// </summary>
        internal static string CountryCode_SLO {
            get {
                return ResourceManager.GetString("CountryCode_SLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  San Marino.
        /// </summary>
        internal static string CountryCode_SMR {
            get {
                return ResourceManager.GetString("CountryCode_SMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Solomon Islands.
        /// </summary>
        internal static string CountryCode_SOL {
            get {
                return ResourceManager.GetString("CountryCode_SOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Somalia.
        /// </summary>
        internal static string CountryCode_SOM {
            get {
                return ResourceManager.GetString("CountryCode_SOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Serbia.
        /// </summary>
        internal static string CountryCode_SRB {
            get {
                return ResourceManager.GetString("CountryCode_SRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sri Lanka.
        /// </summary>
        internal static string CountryCode_SRI {
            get {
                return ResourceManager.GetString("CountryCode_SRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  São Tomé and Príncipe.
        /// </summary>
        internal static string CountryCode_STP {
            get {
                return ResourceManager.GetString("CountryCode_STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sudan.
        /// </summary>
        internal static string CountryCode_SUD {
            get {
                return ResourceManager.GetString("CountryCode_SUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Switzerland.
        /// </summary>
        internal static string CountryCode_SUI {
            get {
                return ResourceManager.GetString("CountryCode_SUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Suriname.
        /// </summary>
        internal static string CountryCode_SUR {
            get {
                return ResourceManager.GetString("CountryCode_SUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Slovakia.
        /// </summary>
        internal static string CountryCode_SVK {
            get {
                return ResourceManager.GetString("CountryCode_SVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sweden.
        /// </summary>
        internal static string CountryCode_SWE {
            get {
                return ResourceManager.GetString("CountryCode_SWE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Swaziland.
        /// </summary>
        internal static string CountryCode_SWZ {
            get {
                return ResourceManager.GetString("CountryCode_SWZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Syria.
        /// </summary>
        internal static string CountryCode_SYR {
            get {
                return ResourceManager.GetString("CountryCode_SYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tanzania.
        /// </summary>
        internal static string CountryCode_TAN {
            get {
                return ResourceManager.GetString("CountryCode_TAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tonga.
        /// </summary>
        internal static string CountryCode_TGA {
            get {
                return ResourceManager.GetString("CountryCode_TGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thailand.
        /// </summary>
        internal static string CountryCode_THA {
            get {
                return ResourceManager.GetString("CountryCode_THA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tajikistan.
        /// </summary>
        internal static string CountryCode_TJK {
            get {
                return ResourceManager.GetString("CountryCode_TJK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Turkmenistan.
        /// </summary>
        internal static string CountryCode_TKM {
            get {
                return ResourceManager.GetString("CountryCode_TKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Timor-Leste.
        /// </summary>
        internal static string CountryCode_TLS {
            get {
                return ResourceManager.GetString("CountryCode_TLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Togo.
        /// </summary>
        internal static string CountryCode_TOG {
            get {
                return ResourceManager.GetString("CountryCode_TOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chinese Taipe [5.
        /// </summary>
        internal static string CountryCode_TPE {
            get {
                return ResourceManager.GetString("CountryCode_TPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Trinidad and Tobago.
        /// </summary>
        internal static string CountryCode_TTO {
            get {
                return ResourceManager.GetString("CountryCode_TTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tunisia.
        /// </summary>
        internal static string CountryCode_TUN {
            get {
                return ResourceManager.GetString("CountryCode_TUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Turkey.
        /// </summary>
        internal static string CountryCode_TUR {
            get {
                return ResourceManager.GetString("CountryCode_TUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tuvalu.
        /// </summary>
        internal static string CountryCode_TUV {
            get {
                return ResourceManager.GetString("CountryCode_TUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  United Arab Emirates.
        /// </summary>
        internal static string CountryCode_UAE {
            get {
                return ResourceManager.GetString("CountryCode_UAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Uganda.
        /// </summary>
        internal static string CountryCode_UGA {
            get {
                return ResourceManager.GetString("CountryCode_UGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ukraine.
        /// </summary>
        internal static string CountryCode_UKR {
            get {
                return ResourceManager.GetString("CountryCode_UKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Uruguay.
        /// </summary>
        internal static string CountryCode_URU {
            get {
                return ResourceManager.GetString("CountryCode_URU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  United States.
        /// </summary>
        internal static string CountryCode_USA {
            get {
                return ResourceManager.GetString("CountryCode_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Uzbekistan.
        /// </summary>
        internal static string CountryCode_UZB {
            get {
                return ResourceManager.GetString("CountryCode_UZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Vanuatu.
        /// </summary>
        internal static string CountryCode_VAN {
            get {
                return ResourceManager.GetString("CountryCode_VAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Venezuela.
        /// </summary>
        internal static string CountryCode_VEN {
            get {
                return ResourceManager.GetString("CountryCode_VEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Vietnam.
        /// </summary>
        internal static string CountryCode_VIE {
            get {
                return ResourceManager.GetString("CountryCode_VIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Saint Vincent and the Grenadines.
        /// </summary>
        internal static string CountryCode_VIN {
            get {
                return ResourceManager.GetString("CountryCode_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Yemen.
        /// </summary>
        internal static string CountryCode_YEM {
            get {
                return ResourceManager.GetString("CountryCode_YEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Zambia.
        /// </summary>
        internal static string CountryCode_ZAM {
            get {
                return ResourceManager.GetString("CountryCode_ZAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Zimbabwe.
        /// </summary>
        internal static string CountryCode_ZIM {
            get {
                return ResourceManager.GetString("CountryCode_ZIM", resourceCulture);
            }
        }
    }
}
