//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Web.Competitions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Web.Competitions.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitors (CSV).
        /// </summary>
        internal static string Adapter_CompetitorsCsv {
            get {
                return ResourceManager.GetString("Adapter_CompetitorsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishLynx Database.
        /// </summary>
        internal static string Adapter_FinishLynxDatabase {
            get {
                return ResourceManager.GetString("Adapter_FinishLynxDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensees (CSV).
        /// </summary>
        internal static string Adapter_LicenseesCsv {
            get {
                return ResourceManager.GetString("Adapter_LicenseesCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYLAPS Orbits.
        /// </summary>
        internal static string Adapter_MylapsOrbits {
            get {
                return ResourceManager.GetString("Adapter_MylapsOrbits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrants (CSV).
        /// </summary>
        internal static string Adapter_RegistrantsCsv {
            get {
                return ResourceManager.GetString("Adapter_RegistrantsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add + New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Address_CountryCode {
            get {
                return ResourceManager.GetString("Address_CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street + Number.
        /// </summary>
        internal static string Address_Line1 {
            get {
                return ResourceManager.GetString("Address_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment, floor, ....
        /// </summary>
        internal static string Address_Line2 {
            get {
                return ResourceManager.GetString("Address_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string Address_PostalCode {
            get {
                return ResourceManager.GetString("Address_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Address_StateOrProvince {
            get {
                return ResourceManager.GetString("Address_StateOrProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Address_Url {
            get {
                return ResourceManager.GetString("Address_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert_Alert {
            get {
                return ResourceManager.GetString("Alert_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The competitor is added with number {0}..
        /// </summary>
        internal static string Alert_CompetitorAdded {
            get {
                return ResourceManager.GetString("Alert_CompetitorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Alert_Confirm {
            get {
                return ResourceManager.GetString("Alert_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Alert_Confirm_No {
            get {
                return ResourceManager.GetString("Alert_Confirm_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Alert_Confirm_Yes {
            get {
                return ResourceManager.GetString("Alert_Confirm_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Alert_Error {
            get {
                return ResourceManager.GetString("Alert_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Alert_Info {
            get {
                return ResourceManager.GetString("Alert_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid license found for this competitor in this competition. The results of this competitor might not be processed..
        /// </summary>
        internal static string Alert_NoPersonLicenseFound {
            get {
                return ResourceManager.GetString("Alert_NoPersonLicenseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {1} records found. Only the first {0} records are shown..
        /// </summary>
        internal static string Alert_RecordsLimited {
            get {
                return ResourceManager.GetString("Alert_RecordsLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Alert_Warning {
            get {
                return ResourceManager.GetString("Alert_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all).
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (automatic).
        /// </summary>
        internal static string AutoValue {
            get {
                return ResourceManager.GetString("AutoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        internal static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Competition_Class {
            get {
                return ResourceManager.GetString("Competition_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Competition_Class_0 {
            get {
                return ResourceManager.GetString("Competition_Class_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string Competition_Class_10 {
            get {
                return ResourceManager.GetString("Competition_Class_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interclub.
        /// </summary>
        internal static string Competition_Class_20 {
            get {
                return ResourceManager.GetString("Competition_Class_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Competition_Class_30 {
            get {
                return ResourceManager.GetString("Competition_Class_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Competition_Class_40 {
            get {
                return ResourceManager.GetString("Competition_Class_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        internal static string Competition_Class_50 {
            get {
                return ResourceManager.GetString("Competition_Class_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        internal static string Competition_Class_60 {
            get {
                return ResourceManager.GetString("Competition_Class_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor Lists.
        /// </summary>
        internal static string Competition_CompetitorLists {
            get {
                return ResourceManager.GetString("Competition_CompetitorLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string Competition_Culture {
            get {
                return ResourceManager.GetString("Competition_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} at {2}..
        /// </summary>
        internal static string Competition_Detail {
            get {
                return ResourceManager.GetString("Competition_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        internal static string Competition_Discipline {
            get {
                return ResourceManager.GetString("Competition_Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Combinations.
        /// </summary>
        internal static string Competition_DistanceCombinations {
            get {
                return ResourceManager.GetString("Competition_DistanceCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distances.
        /// </summary>
        internal static string Competition_Distances {
            get {
                return ResourceManager.GetString("Competition_Distances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Registration.
        /// </summary>
        internal static string Competition_EnableRegistration {
            get {
                return ResourceManager.GetString("Competition_EnableRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string Competition_EndDate {
            get {
                return ResourceManager.GetString("Competition_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends.
        /// </summary>
        internal static string Competition_Ends {
            get {
                return ResourceManager.GetString("Competition_Ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string Competition_EndTime {
            get {
                return ResourceManager.GetString("Competition_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Information.
        /// </summary>
        internal static string Competition_Extra {
            get {
                return ResourceManager.GetString("Competition_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Issuer.
        /// </summary>
        internal static string Competition_LicenseIssuer {
            get {
                return ResourceManager.GetString("Competition_LicenseIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Competition_Location {
            get {
                return ResourceManager.GetString("Competition_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Competition_LocationFlags_1 {
            get {
                return ResourceManager.GetString("Competition_LocationFlags_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        internal static string Competition_LocationFlags_2 {
            get {
                return ResourceManager.GetString("Competition_LocationFlags_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Competition_Name {
            get {
                return ResourceManager.GetString("Competition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Competition_RegistrationSettings {
            get {
                return ResourceManager.GetString("Competition_RegistrationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Competition_Reports {
            get {
                return ResourceManager.GetString("Competition_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        internal static string Competition_Serie {
            get {
                return ResourceManager.GetString("Competition_Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        internal static string Competition_Sponsor {
            get {
                return ResourceManager.GetString("Competition_Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Competition_StartDate {
            get {
                return ResourceManager.GetString("Competition_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts.
        /// </summary>
        internal static string Competition_Starts {
            get {
                return ResourceManager.GetString("Competition_Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Competition_StartTime {
            get {
                return ResourceManager.GetString("Competition_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string Competition_Times {
            get {
                return ResourceManager.GetString("Competition_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        internal static string Competition_Venue {
            get {
                return ResourceManager.GetString("Competition_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitions.
        /// </summary>
        internal static string Competitions {
            get {
                return ResourceManager.GetString("Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition Serie.
        /// </summary>
        internal static string CompetitionSerie {
            get {
                return ResourceManager.GetString("CompetitionSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        internal static string CompetitionSerie_Discipline {
            get {
                return ResourceManager.GetString("CompetitionSerie_Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CompetitionSerie_Name {
            get {
                return ResourceManager.GetString("CompetitionSerie_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string CompetitionSerie_RegistrationSettings {
            get {
                return ResourceManager.GetString("CompetitionSerie_RegistrationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string CompetitionSerie_Season {
            get {
                return ResourceManager.GetString("CompetitionSerie_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition Series.
        /// </summary>
        internal static string CompetitionSeries {
            get {
                return ResourceManager.GetString("CompetitionSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string Competitor_Added {
            get {
                return ResourceManager.GetString("Competitor_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Competitor_Category {
            get {
                return ResourceManager.GetString("Competitor_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Competitor_Class {
            get {
                return ResourceManager.GetString("Competitor_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Combinations.
        /// </summary>
        internal static string Competitor_DistanceCombinations {
            get {
                return ResourceManager.GetString("Competitor_DistanceCombinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string Competitor_LicenseKey {
            get {
                return ResourceManager.GetString("Competitor_LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Competitor_Name {
            get {
                return ResourceManager.GetString("Competitor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Competitor_NationalityCode {
            get {
                return ResourceManager.GetString("Competitor_NationalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        internal static string Competitor_Races {
            get {
                return ResourceManager.GetString("Competitor_Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        internal static string Competitor_ShortName {
            get {
                return ResourceManager.GetString("Competitor_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Number.
        /// </summary>
        internal static string Competitor_StartNumber {
            get {
                return ResourceManager.GetString("Competitor_StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor List.
        /// </summary>
        internal static string CompetitorList {
            get {
                return ResourceManager.GetString("CompetitorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CompetitorList_Category {
            get {
                return ResourceManager.GetString("CompetitorList_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The competitor list is empty..
        /// </summary>
        internal static string CompetitorList_IsEmpty {
            get {
                return ResourceManager.GetString("CompetitorList_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CompetitorList_Name {
            get {
                return ResourceManager.GetString("CompetitorList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No competitors.
        /// </summary>
        internal static string Competitors_IsEmpty {
            get {
                return ResourceManager.GetString("Competitors_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        internal static string Contact_Email {
            get {
                return ResourceManager.GetString("Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Contact_OrganizationName {
            get {
                return ResourceManager.GetString("Contact_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Contact_Phone {
            get {
                return ResourceManager.GetString("Contact_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (custom).
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        internal static string DefaultCountryCode {
            get {
                return ResourceManager.GetString("DefaultCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplines.
        /// </summary>
        internal static string Disciplines {
            get {
                return ResourceManager.GetString("Disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        internal static string Distance_Classification {
            get {
                return ResourceManager.GetString("Distance_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Numbering.
        /// </summary>
        internal static string Distance_ContinuousNumbering {
            get {
                return ResourceManager.GetString("Distance_ContinuousNumbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        internal static string Distance_Discipline {
            get {
                return ResourceManager.GetString("Distance_Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string Distance_Draw {
            get {
                return ResourceManager.GetString("Distance_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends.
        /// </summary>
        internal static string Distance_Ends {
            get {
                return ResourceManager.GetString("Distance_Ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Weather.
        /// </summary>
        internal static string Distance_EndWeather {
            get {
                return ResourceManager.GetString("Distance_EndWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number From.
        /// </summary>
        internal static string Distance_FirstHeat {
            get {
                return ResourceManager.GetString("Distance_FirstHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance is empty..
        /// </summary>
        internal static string Distance_IsEmpty {
            get {
                return ResourceManager.GetString("Distance_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Distance_Name {
            get {
                return ResourceManager.GetString("Distance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Distance_Number {
            get {
                return ResourceManager.GetString("Distance_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Distance_Reports {
            get {
                return ResourceManager.GetString("Distance_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Distance_Result {
            get {
                return ResourceManager.GetString("Distance_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        internal static string Distance_Rounds {
            get {
                return ResourceManager.GetString("Distance_Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rounds.
        /// </summary>
        internal static string Distance_RoundsValueFormat {
            get {
                return ResourceManager.GetString("Distance_RoundsValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Distance_StartDate {
            get {
                return ResourceManager.GetString("Distance_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mode.
        /// </summary>
        internal static string Distance_StartMode {
            get {
                return ResourceManager.GetString("Distance_StartMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts.
        /// </summary>
        internal static string Distance_Starts {
            get {
                return ResourceManager.GetString("Distance_Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Distance_StartTime {
            get {
                return ResourceManager.GetString("Distance_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Weather.
        /// </summary>
        internal static string Distance_StartWeather {
            get {
                return ResourceManager.GetString("Distance_StartWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Length.
        /// </summary>
        internal static string Distance_TrackLength {
            get {
                return ResourceManager.GetString("Distance_TrackLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance_Value {
            get {
                return ResourceManager.GetString("Distance_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string Distance_Weather {
            get {
                return ResourceManager.GetString("Distance_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Combination.
        /// </summary>
        internal static string DistanceCombination {
            get {
                return ResourceManager.GetString("DistanceCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Filter.
        /// </summary>
        internal static string DistanceCombination_CategoryFilter {
            get {
                return ResourceManager.GetString("DistanceCombination_CategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string DistanceCombination_Class {
            get {
                return ResourceManager.GetString("DistanceCombination_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distances.
        /// </summary>
        internal static string DistanceCombination_Distances {
            get {
                return ResourceManager.GetString("DistanceCombination_Distances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set indicative start time.
        /// </summary>
        internal static string DistanceCombination_HasStarts {
            get {
                return ResourceManager.GetString("DistanceCombination_HasStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DistanceCombination_Name {
            get {
                return ResourceManager.GetString("DistanceCombination_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string DistanceCombination_Number {
            get {
                return ResourceManager.GetString("DistanceCombination_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string DistanceCombination_StartDate {
            get {
                return ResourceManager.GetString("DistanceCombination_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string DistanceCombination_StartTime {
            get {
                return ResourceManager.GetString("DistanceCombination_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitute.
        /// </summary>
        internal static string DistanceCombinationCompetitor_Reserve {
            get {
                return ResourceManager.GetString("DistanceCombinationCompetitor_Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DistanceCombinationCompetitor_Status {
            get {
                return ResourceManager.GetString("DistanceCombinationCompetitor_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string DistanceCombinationCompetitor_Status_0 {
            get {
                return ResourceManager.GetString("DistanceCombinationCompetitor_Status_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string DistanceCombinationCompetitor_Status_1 {
            get {
                return ResourceManager.GetString("DistanceCombinationCompetitor_Status_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        internal static string DistanceCombinationCompetitor_Status_2 {
            get {
                return ResourceManager.GetString("DistanceCombinationCompetitor_Status_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string DistanceCombinationRegistrationSettings_Price {
            get {
                return ResourceManager.GetString("DistanceCombinationRegistrationSettings_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heat is empty..
        /// </summary>
        internal static string Heat_IsEmpty {
            get {
                return ResourceManager.GetString("Heat_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter.
        /// </summary>
        internal static string Import_Adapter {
            get {
                return ResourceManager.GetString("Import_Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Import_Files {
            get {
                return ResourceManager.GetString("Import_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        internal static string Invitee_Email {
            get {
                return ResourceManager.GetString("Invitee_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        internal static string Invitee_IsInvited {
            get {
                return ResourceManager.GetString("Invitee_IsInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitute.
        /// </summary>
        internal static string Invitee_Reserve {
            get {
                return ResourceManager.GetString("Invitee_Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Invitees.
        /// </summary>
        internal static string Invitees_Add {
            get {
                return ResourceManager.GetString("Invitees_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensees.
        /// </summary>
        internal static string Invitees_Keys {
            get {
                return ResourceManager.GetString("Invitees_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate multiple licensees using new lines, commas or semicolons..
        /// </summary>
        internal static string Invitees_Keys_Help {
            get {
                return ResourceManager.GetString("Invitees_Keys_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string LicensePurchases_Amount {
            get {
                return ResourceManager.GetString("LicensePurchases_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string LicensePurchases_Count {
            get {
                return ResourceManager.GetString("LicensePurchases_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat {0}.
        /// </summary>
        internal static string MassStartDistance_HeatFormat {
            get {
                return ResourceManager.GetString("MassStartDistance_HeatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM y.
        /// </summary>
        internal static string MediumDate {
            get {
                return ResourceManager.GetString("MediumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Name_FirstName {
            get {
                return ResourceManager.GetString("Name_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initials.
        /// </summary>
        internal static string Name_Initials {
            get {
                return ResourceManager.GetString("Name_Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Name_Surname {
            get {
                return ResourceManager.GetString("Name_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Name_SurnamePrefix {
            get {
                return ResourceManager.GetString("Name_SurnamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        internal static string Numbering {
            get {
                return ResourceManager.GetString("Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        internal static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Person_Address {
            get {
                return ResourceManager.GetString("Person_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string Person_BirthDate {
            get {
                return ResourceManager.GetString("Person_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string Person_Details {
            get {
                return ResourceManager.GetString("Person_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        internal static string Person_Email {
            get {
                return ResourceManager.GetString("Person_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Person_Name {
            get {
                return ResourceManager.GetString("Person_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Person_NationalityCode {
            get {
                return ResourceManager.GetString("Person_NationalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Person_Phone {
            get {
                return ResourceManager.GetString("Person_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string PersonCategories {
            get {
                return ResourceManager.GetString("PersonCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string PersonCategory_Code {
            get {
                return ResourceManager.GetString("PersonCategory_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PersonCategory_Name {
            get {
                return ResourceManager.GetString("PersonCategory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string PersonCompetitors {
            get {
                return ResourceManager.GetString("PersonCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all categories).
        /// </summary>
        internal static string PersonLicense_Categories_All {
            get {
                return ResourceManager.GetString("PersonLicense_Categories_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string PersonLicense_Category {
            get {
                return ResourceManager.GetString("PersonLicense_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string PersonLicense_Class {
            get {
                return ResourceManager.GetString("PersonLicense_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string PersonLicense_Club {
            get {
                return ResourceManager.GetString("PersonLicense_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        internal static string PersonLicense_Discipline {
            get {
                return ResourceManager.GetString("PersonLicense_Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all disciplines).
        /// </summary>
        internal static string PersonLicense_Disciplines_All {
            get {
                return ResourceManager.GetString("PersonLicense_Disciplines_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary License.
        /// </summary>
        internal static string PersonLicense_Flag_1 {
            get {
                return ResourceManager.GetString("PersonLicense_Flag_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PersonLicense_Flags {
            get {
                return ResourceManager.GetString("PersonLicense_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string PersonLicense_IsExpired {
            get {
                return ResourceManager.GetString("PersonLicense_IsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        internal static string PersonLicense_Issuer {
            get {
                return ResourceManager.GetString("PersonLicense_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all issuers).
        /// </summary>
        internal static string PersonLicense_Issuers_All {
            get {
                return ResourceManager.GetString("PersonLicense_Issuers_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string PersonLicense_Key {
            get {
                return ResourceManager.GetString("PersonLicense_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string PersonLicense_Number {
            get {
                return ResourceManager.GetString("PersonLicense_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string PersonLicense_Season {
            get {
                return ResourceManager.GetString("PersonLicense_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        internal static string PersonLicense_Sponsor {
            get {
                return ResourceManager.GetString("PersonLicense_Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transponders.
        /// </summary>
        internal static string PersonLicense_Transponders {
            get {
                return ResourceManager.GetString("PersonLicense_Transponders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        internal static string PersonLicense_ValidFrom {
            get {
                return ResourceManager.GetString("PersonLicense_ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity.
        /// </summary>
        internal static string PersonLicense_Validity {
            get {
                return ResourceManager.GetString("PersonLicense_Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string PersonLicense_ValidityFormat {
            get {
                return ResourceManager.GetString("PersonLicense_ValidityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        internal static string PersonLicense_ValidTo {
            get {
                return ResourceManager.GetString("PersonLicense_ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string PersonLicenses {
            get {
                return ResourceManager.GetString("PersonLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Times.
        /// </summary>
        internal static string Race_Laps {
            get {
                return ResourceManager.GetString("Race_Laps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no intermediate times..
        /// </summary>
        internal static string Race_Laps_IsEmpty {
            get {
                return ResourceManager.GetString("Race_Laps_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Race_Name {
            get {
                return ResourceManager.GetString("Race_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        internal static string Race_PB {
            get {
                return ResourceManager.GetString("Race_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Best.
        /// </summary>
        internal static string Race_PersonalBest {
            get {
                return ResourceManager.GetString("Race_PersonalBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Race_Points {
            get {
                return ResourceManager.GetString("Race_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Race_Result_State {
            get {
                return ResourceManager.GetString("Race_Result_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string Race_Result_State_0 {
            get {
                return ResourceManager.GetString("Race_Result_State_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string Race_Result_State_1 {
            get {
                return ResourceManager.GetString("Race_Result_State_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated.
        /// </summary>
        internal static string Race_Result_State_2 {
            get {
                return ResourceManager.GetString("Race_Result_State_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Race_Result_State_3 {
            get {
                return ResourceManager.GetString("Race_Result_State_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Race_Result_State_4 {
            get {
                return ResourceManager.GetString("Race_Result_State_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_1 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Finished.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_2 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disqualified.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_3 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_4 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NS.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_Code_1 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_Code_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NF.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_Code_2 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_Code_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DQ.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_Code_3 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_Code_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WD.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_Code_4 {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_Code_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_Code_null {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_Code_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Race_Result_TimeInvalidReason_null {
            get {
                return ResourceManager.GetString("Race_Result_TimeInvalidReason_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Race_Results {
            get {
                return ResourceManager.GetString("Race_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Time.
        /// </summary>
        internal static string Race_Time {
            get {
                return ResourceManager.GetString("Race_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall.
        /// </summary>
        internal static string Race_Time_TimeInfo_1 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Record.
        /// </summary>
        internal static string Race_Time_TimeInfo_16 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Race_Time_TimeInfo_2 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Record.
        /// </summary>
        internal static string Race_Time_TimeInfo_32 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Best.
        /// </summary>
        internal static string Race_Time_TimeInfo_4 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Record.
        /// </summary>
        internal static string Race_Time_TimeInfo_8 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        internal static string Race_Time_TimeInfo_Code_1 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_Code_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        internal static string Race_Time_TimeInfo_Code_16 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_Code_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS.
        /// </summary>
        internal static string Race_Time_TimeInfo_Code_2 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_Code_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WR.
        /// </summary>
        internal static string Race_Time_TimeInfo_Code_32 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_Code_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        internal static string Race_Time_TimeInfo_Code_4 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_Code_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        internal static string Race_Time_TimeInfo_Code_8 {
            get {
                return ResourceManager.GetString("Race_Time_TimeInfo_Code_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transponders.
        /// </summary>
        internal static string Race_Transponders {
            get {
                return ResourceManager.GetString("Race_Transponders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Race_UserResult {
            get {
                return ResourceManager.GetString("Race_UserResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations.
        /// </summary>
        internal static string Registrations {
            get {
                return ResourceManager.GetString("Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Registrations_Amount {
            get {
                return ResourceManager.GetString("Registrations_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Registrations_ConfirmedCount {
            get {
                return ResourceManager.GetString("Registrations_ConfirmedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrations.
        /// </summary>
        internal static string Registrations_Count {
            get {
                return ResourceManager.GetString("Registrations_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        internal static string Registrations_WithdrawnCount {
            get {
                return ResourceManager.GetString("Registrations_WithdrawnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Registrations.
        /// </summary>
        internal static string RegistrationSettings_AllowedRegistrations {
            get {
                return ResourceManager.GetString("RegistrationSettings_AllowedRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition Licensees.
        /// </summary>
        internal static string RegistrationSettings_AllowedRegistrations_1 {
            get {
                return ResourceManager.GetString("RegistrationSettings_AllowedRegistrations_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Licensees.
        /// </summary>
        internal static string RegistrationSettings_AllowedRegistrations_2 {
            get {
                return ResourceManager.GetString("RegistrationSettings_AllowedRegistrations_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations.
        /// </summary>
        internal static string RegistrationSettings_AllowedRegistrations_4 {
            get {
                return ResourceManager.GetString("RegistrationSettings_AllowedRegistrations_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Closes.
        /// </summary>
        internal static string RegistrationSettings_Closes {
            get {
                return ResourceManager.GetString("RegistrationSettings_Closes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition Price.
        /// </summary>
        internal static string RegistrationSettings_CompetitionPrice {
            get {
                return ResourceManager.GetString("RegistrationSettings_CompetitionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Competitors.
        /// </summary>
        internal static string RegistrationSettings_CompetitorListGrouping {
            get {
                return ResourceManager.GetString("RegistrationSettings_CompetitorListGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Grouping.
        /// </summary>
        internal static string RegistrationSettings_CompetitorListGrouping_0 {
            get {
                return ResourceManager.GetString("RegistrationSettings_CompetitorListGrouping_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Gender.
        /// </summary>
        internal static string RegistrationSettings_CompetitorListGrouping_1 {
            get {
                return ResourceManager.GetString("RegistrationSettings_CompetitorListGrouping_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Category.
        /// </summary>
        internal static string RegistrationSettings_CompetitorListGrouping_2 {
            get {
                return ResourceManager.GetString("RegistrationSettings_CompetitorListGrouping_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor List URL.
        /// </summary>
        internal static string RegistrationSettings_CompetitorListUri {
            get {
                return ResourceManager.GetString("RegistrationSettings_CompetitorListUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string RegistrationSettings_Contact {
            get {
                return ResourceManager.GetString("RegistrationSettings_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Information.
        /// </summary>
        internal static string RegistrationSettings_Extra {
            get {
                return ResourceManager.GetString("RegistrationSettings_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string RegistrationSettings_InvitationFooter {
            get {
                return ResourceManager.GetString("RegistrationSettings_InvitationFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text will be inserted in the e-mail template of the competitor registration system. You can use HTML mark-up..
        /// </summary>
        internal static string RegistrationSettings_InvitationFooter_Help {
            get {
                return ResourceManager.GetString("RegistrationSettings_InvitationFooter_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string RegistrationSettings_InvitationIntroduction {
            get {
                return ResourceManager.GetString("RegistrationSettings_InvitationIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations.
        /// </summary>
        internal static string RegistrationSettings_Invitations {
            get {
                return ResourceManager.GetString("RegistrationSettings_Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitees.
        /// </summary>
        internal static string RegistrationSettings_Invitees {
            get {
                return ResourceManager.GetString("RegistrationSettings_Invitees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string RegistrationSettings_IsClosed {
            get {
                return ResourceManager.GetString("RegistrationSettings_IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Opens.
        /// </summary>
        internal static string RegistrationSettings_Opens {
            get {
                return ResourceManager.GetString("RegistrationSettings_Opens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Reference.
        /// </summary>
        internal static string RegistrationSettings_PaymentReference {
            get {
                return ResourceManager.GetString("RegistrationSettings_PaymentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string RegistrationSettings_Price {
            get {
                return ResourceManager.GetString("RegistrationSettings_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration URL.
        /// </summary>
        internal static string RegistrationSettings_RegistrationUri {
            get {
                return ResourceManager.GetString("RegistrationSettings_RegistrationUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Registration for Serie.
        /// </summary>
        internal static string RegistrationSettings_RequireSerieRegistration {
            get {
                return ResourceManager.GetString("RegistrationSettings_RequireSerieRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie Price.
        /// </summary>
        internal static string RegistrationSettings_SeriePrice {
            get {
                return ResourceManager.GetString("RegistrationSettings_SeriePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Times.
        /// </summary>
        internal static string RegistrationSettings_Times {
            get {
                return ResourceManager.GetString("RegistrationSettings_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string RegistrationSettings_Uris {
            get {
                return ResourceManager.GetString("RegistrationSettings_Uris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber.
        /// </summary>
        internal static string Renumber {
            get {
                return ResourceManager.GetString("Renumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature List.
        /// </summary>
        internal static string Report_CompetitorSignatureLists {
            get {
                return ResourceManager.GetString("Report_CompetitorSignatureLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Report_Download {
            get {
                return ResourceManager.GetString("Report_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Report_Format {
            get {
                return ResourceManager.GetString("Report_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Report_Name {
            get {
                return ResourceManager.GetString("Report_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string ShortDate {
            get {
                return ResourceManager.GetString("ShortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Statistics_Transactions {
            get {
                return ResourceManager.GetString("Statistics_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        internal static string TeamCompetitor_Members {
            get {
                return ResourceManager.GetString("TeamCompetitor_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person List.
        /// </summary>
        internal static string TeamCompetitorList_PersonList {
            get {
                return ResourceManager.GetString("TeamCompetitorList_PersonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string TeamCompetitors {
            get {
                return ResourceManager.GetString("TeamCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Transponder_Label {
            get {
                return ResourceManager.GetString("Transponder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Transponder_Type {
            get {
                return ResourceManager.GetString("Transponder_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transponders.
        /// </summary>
        internal static string Transponders {
            get {
                return ResourceManager.GetString("Transponders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transponders..
        /// </summary>
        internal static string Transponders_IsEmpty {
            get {
                return ResourceManager.GetString("Transponders_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Pressure.
        /// </summary>
        internal static string Weather_AirPressure {
            get {
                return ResourceManager.GetString("Weather_AirPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Weather_AirTemperature {
            get {
                return ResourceManager.GetString("Weather_AirTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Weather_Humidity {
            get {
                return ResourceManager.GetString("Weather_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature (track).
        /// </summary>
        internal static string Weather_TrackTemperature {
            get {
                return ResourceManager.GetString("Weather_TrackTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        internal static string Weather_WindSpeed {
            get {
                return ResourceManager.GetString("Weather_WindSpeed", resourceCulture);
            }
        }
    }
}
