// <auto-generated />
namespace Emando.Vantage.Components.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NumberPrefixAndVenueClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberPrefixAndVenueClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201510042148417_NumberPrefixAndVenueClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
