//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Workflows.Competitions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Workflows.Competitions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot activate the race because the distance is not activated..
        /// </summary>
        internal static string CannotActivateRace {
            get {
                return ResourceManager.GetString("CannotActivateRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition is null..
        /// </summary>
        internal static string DistanceCompetitionIsNull {
            get {
                return ResourceManager.GetString("DistanceCompetitionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete races from {0}: the distance has results..
        /// </summary>
        internal static string DistanceHasResults {
            get {
                return ResourceManager.GetString("DistanceHasResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation results in a collission of the heat {1} in round {0}..
        /// </summary>
        internal static string HeatCollission {
            get {
                return ResourceManager.GetString("HeatCollission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation results in an invalid heat {0}..
        /// </summary>
        internal static string InvalidHeat {
            get {
                return ResourceManager.GetString("InvalidHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is null..
        /// </summary>
        internal static string PersonCompetitorPersonIsNull {
            get {
                return ResourceManager.GetString("PersonCompetitorPersonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation could not be completed. The competitor or its number {0} already exists on the competitor list..
        /// </summary>
        internal static string StartNumberCollission {
            get {
                return ResourceManager.GetString("StartNumberCollission", resourceCulture);
            }
        }
    }
}
