//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category does not match the filter..
        /// </summary>
        internal static string CategoryMatchFailed {
            get {
                return ResourceManager.GetString("CategoryMatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category &apos;{1}&apos; does not match filter &apos;{0}&apos;..
        /// </summary>
        internal static string CategoryMatchFailedFormat {
            get {
                return ResourceManager.GetString("CategoryMatchFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class does not match the minimum class..
        /// </summary>
        internal static string ClassMatchFailed {
            get {
                return ResourceManager.GetString("ClassMatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &apos;{1}&apos; does not match class &apos;{0}&apos;..
        /// </summary>
        internal static string ClassMatchFailedFormat {
            get {
                return ResourceManager.GetString("ClassMatchFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club code does not match the filter..
        /// </summary>
        internal static string ClubCodeMatchFailed {
            get {
                return ResourceManager.GetString("ClubCodeMatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club code &apos;{0}&apos; does not match filter &apos;{1}&apos;..
        /// </summary>
        internal static string ClubCodeMatchFailedFormat {
            get {
                return ResourceManager.GetString("ClubCodeMatchFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified club could not be found..
        /// </summary>
        internal static string ClubNotFound {
            get {
                return ResourceManager.GetString("ClubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified country could not be found..
        /// </summary>
        internal static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data failed because of dependent data..
        /// </summary>
        internal static string DependingDataDeleteFailed {
            get {
                return ResourceManager.GetString("DependingDataDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The home venue does not match the filter..
        /// </summary>
        internal static string HomeVenueMatchFailed {
            get {
                return ResourceManager.GetString("HomeVenueMatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue code &apos;{0}&apos; does not match filter &apos;{1}&apos;..
        /// </summary>
        internal static string HomeVenueMatchFailedFormat {
            get {
                return ResourceManager.GetString("HomeVenueMatchFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified discipline is invalid..
        /// </summary>
        internal static string InvalidDiscipline {
            get {
                return ResourceManager.GetString("InvalidDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation results in a collission of unique numbers..
        /// </summary>
        internal static string NumberCollission {
            get {
                return ResourceManager.GetString("NumberCollission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified category could not be found..
        /// </summary>
        internal static string PersonCategoryNotFound {
            get {
                return ResourceManager.GetString("PersonCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license {0}/{1}/{2} could not be found..
        /// </summary>
        internal static string PersonLicenseNotFound {
            get {
                return ResourceManager.GetString("PersonLicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified person could not be found..
        /// </summary>
        internal static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified transponder bag could not be found..
        /// </summary>
        internal static string TransponderBagNotFound {
            get {
                return ResourceManager.GetString("TransponderBagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified transponder could not be found..
        /// </summary>
        internal static string TransponderNotFound {
            get {
                return ResourceManager.GetString("TransponderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified venue could not be found..
        /// </summary>
        internal static string VenueNotFound {
            get {
                return ResourceManager.GetString("VenueNotFound", resourceCulture);
            }
        }
    }
}
