//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Data.Competitions.SpeedSkating.LongTrack.Sara2.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Data.Competitions.SpeedSkating.LongTrack.Sara2.Test.Properties.Res" +
                            "ources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #----- Pair I Snr LongName                  Code    Cat
        ///#SN Pas DID  Trans-L1  Trans-R1  Trans-L2  Trans-R2  Trans-L3  Trans-R3  Trans-L4  Trans-R4
        ///#------------------------------------------------------------------------------------------
        ///#-PAIR: 001 I 011 Susanna Potka             FIN     DSA 
        ///##      016  102064350 101969251
        ///011 001 003  CZ-01054  CX-05955
        ///#-----: 001 O 000                                       
        ///## 
        ///000 001 003
        ///#-PAIR: 002 I 030 Daniela Oltean            ROU     DSA 
        ///##      01 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AFile {
            get {
                return ResourceManager.GetString("AFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011 000 E #01: Dames Neo-/Senioren 500 meter
        ///001 I 021 Annouk vd Weijden         HA      DN3 HA03735 VD WEIJDEN       00:41.1900 00500 m ???.??? 041.530 00:41.5300 (OK) 00:41.3700 
        ///001 O 000
        ///002 I 006 Anice Das                 HV      DN3 HV31175 DAS              00:41.0100 00500 m ???.??? 040.710 00:40.7100 (OK) 00:41.0100 
        ///002 O 008 Paulien van Deutekom      DH      DSA DH33020 VAN DEUTEKOM     00:39.6700 00500 m ???.??? 039.960 00:39.9600 (OK) 00:40.8900 
        ///003 I 005 Wieteke Cramer            HV       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CFile {
            get {
                return ResourceManager.GetString("CFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR. |AFSTAND  |DATUM     |BAAN|ET-filenaam
        ///----+---------+----------+----+-----------
        ///  1  500  m.   04/11/2012  HV  C00500M.D01   Dames Neo-/Senioren 500 meter   #20080105CVNKS-D_
        ///  2  500  m.   04/11/2012  HV  C00500M.D02   Heren Neo-/Senioren 500 meter   #20080105CVNKS-H_
        ///  3  1000 m.   05/11/2012  HV  C01000M.D03   Dames Neo-/Senioren 1000 meter  #20080105CVNKS-D_
        ///  4  1000 m.   05/01/2008  HV  C01000M.D04   Heren Neo-/Senioren 1000 meter  #20080105CVNKS-H_
        ///  5  500  m.   06/01/2008  HV  C00500M.D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaraInfFile {
            get {
                return ResourceManager.GetString("SaraInfFile", resourceCulture);
            }
        }
    }
}
