//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emando.Vantage.Components.Adapters.KNSB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emando.Vantage.Components.Adapters.KNSB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance combination number &apos;{0}&apos; could not be found at line {1}..
        /// </summary>
        internal static string DistanceCombinationNumberNotFound {
            get {
                return ResourceManager.GetString("DistanceCombinationNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bag number &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidBagNumber {
            get {
                return ResourceManager.GetString("InvalidBagNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid birth date &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid class &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidClass {
            get {
                return ResourceManager.GetString("InvalidClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid competitor class at line {0}..
        /// </summary>
        internal static string InvalidCompetitorClass {
            get {
                return ResourceManager.GetString("InvalidCompetitorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid distance combination number &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidDistanceCombinationNumber {
            get {
                return ResourceManager.GetString("InvalidDistanceCombinationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name pattern..
        /// </summary>
        internal static string InvalidFileNamePattern {
            get {
                return ResourceManager.GetString("InvalidFileNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gender &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid lane &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidLane {
            get {
                return ResourceManager.GetString("InvalidLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start number &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidStartNumber {
            get {
                return ResourceManager.GetString("InvalidStartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transponder label &apos;{0}&apos; type &apos;{1}&apos; at line {2}..
        /// </summary>
        internal static string InvalidTransponderLabel {
            get {
                return ResourceManager.GetString("InvalidTransponderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transponder set number &apos;{0}&apos; at line {1}..
        /// </summary>
        internal static string InvalidTransponderSetNumber {
            get {
                return ResourceManager.GetString("InvalidTransponderSetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key &apos;{0}&apos; of discipline &apos;{1}&apos; of issuer &apos;{2}&apos; could not be found at line {3}..
        /// </summary>
        internal static string PersonLicenseKeyNotFound {
            get {
                return ResourceManager.GetString("PersonLicenseKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race with start number {0} at lane {1} not found at line {2}..
        /// </summary>
        internal static string RaceNotFound {
            get {
                return ResourceManager.GetString("RaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A race in pair {0} and lane {1} could not be found..
        /// </summary>
        internal static string RaceNotFoundFormat {
            get {
                return ResourceManager.GetString("RaceNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting at least {0} fields at line {1}..
        /// </summary>
        internal static string TooFewFields {
            get {
                return ResourceManager.GetString("TooFewFields", resourceCulture);
            }
        }
    }
}
